### ISSUE TITLE
Details/Summary Elements on Long Texts

### ISSUE THREAD

**Issue by p4pnl** [privacypatterns/patterns#17]
@npdoty @mohit 

Since MarkDown supports certain HTML elements, including `<details><summary>More...</summary></details>`, does Hyde therefore support this as well, and should we make use of it either a) in the template or b) when necessary?
  
E.g.
## Problem
[Some paragraphs about the problem here]
#### Forces and Concerns
<details> 
  <summary>
    More...
  </summary>
[Some <b>bold text</b> here ontop a horizontal line]
<hr>
</details>

<br>Edit: note that any text within `<details>` will lose MarkDown formatting, but retain HTML.

**Comment by npdoty** [comment]
I think HTML does pass through, so it should function. That said, I'm not sure it'll be something we want to use commonly. The patterns are mostly made up of text already, and I think most people are happy to read text, or skim over paragraphs they're not interested in.
