### ISSUE TITLE
CSS "position: sticky" for Pattern Table of Contents

### ISSUE THREAD

**Issue by p4pnl** [privacypatterns/patterns#19]
Edit: Resolved by https://github.com/privacypatterns/privacypatterns/issues/81

Something that may aid otherwise long patterns is a ToC which 'sticks' to the top as you scroll beyond its initial position. That way one may skip long sections without a lot of scrolling.

This is achieved by adding `position: sticky; position: webkit-sticky; top: 0px` to the `toc` class.

It also appears to look better after removing `width: 40%` as currently there is some extra whitespace to the right.

Edit: [see example change here](https://github.com/p4pnl/privacypatterns/commit/d564dfaaa968eed721634b95114e189aa13505d9). Unfortunately GitHub adds a newline upon editing.

**Comment by HecticSeptic** [comment]
@npdoty could you check if the above is an acceptable change to the CSS?

Also, is there a reasoning behind the `body margin:22px 155px 22px 95px` and `#container max-width:1064px`? It seems to me that changing `155` to `95` and either removing `max-width` from `#container` or setting it to `margin:auto` (for centering) looks best.
